#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.225
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBArtikelDbLayer.Dtx
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBArtikel")]
	public partial class DtxDBArtikelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertArtikel(Artikel instance);
    partial void UpdateArtikel(Artikel instance);
    partial void DeleteArtikel(Artikel instance);
    partial void InsertLieferanten(Lieferanten instance);
    partial void UpdateLieferanten(Lieferanten instance);
    partial void DeleteLieferanten(Lieferanten instance);
    partial void InsertProdukte(Produkte instance);
    partial void UpdateProdukte(Produkte instance);
    partial void DeleteProdukte(Produkte instance);
    partial void InsertAuslieferung(Auslieferung instance);
    partial void UpdateAuslieferung(Auslieferung instance);
    partial void DeleteAuslieferung(Auslieferung instance);
    #endregion
		
		public DtxDBArtikelDataContext() : 
				base(global::DBArtikelDbLayer.Properties.Settings.Default.DBArtikelConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DtxDBArtikelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtxDBArtikelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtxDBArtikelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtxDBArtikelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Artikel> Artikels
		{
			get
			{
				return this.GetTable<Artikel>();
			}
		}
		
		public System.Data.Linq.Table<Lieferanten> Lieferantens
		{
			get
			{
				return this.GetTable<Lieferanten>();
			}
		}
		
		public System.Data.Linq.Table<Produkte> Produktes
		{
			get
			{
				return this.GetTable<Produkte>();
			}
		}
		
		public System.Data.Linq.Table<Auslieferung> Auslieferung
		{
			get
			{
				return this.GetTable<Auslieferung>();
			}
		}
		
		public System.Data.Linq.Table<ArtikelDetailsView> ArtikelDetailsView
		{
			get
			{
				return this.GetTable<ArtikelDetailsView>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lagerbestand")]
		public ISingleResult<lagerbestandResult> lagerbestand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<lagerbestandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListeAlleArtikelZumLieferanten")]
		public ISingleResult<ListeAlleArtikelZumLieferantenResult> ListeAlleArtikelZumLieferanten([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string lieferant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lieferant);
			return ((ISingleResult<ListeAlleArtikelZumLieferantenResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Artikel")]
	public partial class Artikel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _artnr;
		
		private int _lfnr;
		
		private int _pnr;
		
		private System.Nullable<int> _vorrat;
		
		private System.Nullable<decimal> _preis;
		
		private EntityRef<Lieferanten> _Lieferanten;
		
		private EntityRef<Produkte> _Produkte;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnartnrChanging(int value);
    partial void OnartnrChanged();
    partial void OnlfnrChanging(int value);
    partial void OnlfnrChanged();
    partial void OnpnrChanging(int value);
    partial void OnpnrChanged();
    partial void OnvorratChanging(System.Nullable<int> value);
    partial void OnvorratChanged();
    partial void OnpreisChanging(System.Nullable<decimal> value);
    partial void OnpreisChanged();
    #endregion
		
		public Artikel()
		{
			this._Lieferanten = default(EntityRef<Lieferanten>);
			this._Produkte = default(EntityRef<Produkte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artnr", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int artnr
		{
			get
			{
				return this._artnr;
			}
			set
			{
				if ((this._artnr != value))
				{
					this.OnartnrChanging(value);
					this.SendPropertyChanging();
					this._artnr = value;
					this.SendPropertyChanged("artnr");
					this.OnartnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lfnr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int lfnr
		{
			get
			{
				return this._lfnr;
			}
			set
			{
				if ((this._lfnr != value))
				{
					if (this._Lieferanten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlfnrChanging(value);
					this.SendPropertyChanging();
					this._lfnr = value;
					this.SendPropertyChanged("lfnr");
					this.OnlfnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pnr
		{
			get
			{
				return this._pnr;
			}
			set
			{
				if ((this._pnr != value))
				{
					if (this._Produkte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpnrChanging(value);
					this.SendPropertyChanging();
					this._pnr = value;
					this.SendPropertyChanged("pnr");
					this.OnpnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorrat", DbType="Int")]
		public System.Nullable<int> vorrat
		{
			get
			{
				return this._vorrat;
			}
			set
			{
				if ((this._vorrat != value))
				{
					this.OnvorratChanging(value);
					this.SendPropertyChanging();
					this._vorrat = value;
					this.SendPropertyChanged("vorrat");
					this.OnvorratChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preis", DbType="Money")]
		public System.Nullable<decimal> preis
		{
			get
			{
				return this._preis;
			}
			set
			{
				if ((this._preis != value))
				{
					this.OnpreisChanging(value);
					this.SendPropertyChanging();
					this._preis = value;
					this.SendPropertyChanged("preis");
					this.OnpreisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lieferanten_Artikel", Storage="_Lieferanten", ThisKey="lfnr", OtherKey="lfnr", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Lieferanten Lieferanten
		{
			get
			{
				return this._Lieferanten.Entity;
			}
			set
			{
				Lieferanten previousValue = this._Lieferanten.Entity;
				if (((previousValue != value) 
							|| (this._Lieferanten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lieferanten.Entity = null;
						previousValue.Artikels.Remove(this);
					}
					this._Lieferanten.Entity = value;
					if ((value != null))
					{
						value.Artikels.Add(this);
						this._lfnr = value.lfnr;
					}
					else
					{
						this._lfnr = default(int);
					}
					this.SendPropertyChanged("Lieferanten");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkte_Artikel", Storage="_Produkte", ThisKey="pnr", OtherKey="pnr", IsForeignKey=true)]
		public Produkte Produkte
		{
			get
			{
				return this._Produkte.Entity;
			}
			set
			{
				Produkte previousValue = this._Produkte.Entity;
				if (((previousValue != value) 
							|| (this._Produkte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produkte.Entity = null;
						previousValue.Artikels.Remove(this);
					}
					this._Produkte.Entity = value;
					if ((value != null))
					{
						value.Artikels.Add(this);
						this._pnr = value.pnr;
					}
					else
					{
						this._pnr = default(int);
					}
					this.SendPropertyChanged("Produkte");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lieferanten")]
	public partial class Lieferanten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lfnr;
		
		private string _name;
		
		private string _email;
		
		private string _plz;
		
		private EntitySet<Artikel> _Artikels;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlfnrChanging(int value);
    partial void OnlfnrChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnplzChanging(string value);
    partial void OnplzChanged();
    #endregion
		
		public Lieferanten()
		{
			this._Artikels = new EntitySet<Artikel>(new Action<Artikel>(this.attach_Artikels), new Action<Artikel>(this.detach_Artikels));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lfnr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int lfnr
		{
			get
			{
				return this._lfnr;
			}
			set
			{
				if ((this._lfnr != value))
				{
					this.OnlfnrChanging(value);
					this.SendPropertyChanging();
					this._lfnr = value;
					this.SendPropertyChanged("lfnr");
					this.OnlfnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(1000)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(1000)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plz", DbType="NChar(5)")]
		public string plz
		{
			get
			{
				return this._plz;
			}
			set
			{
				if ((this._plz != value))
				{
					this.OnplzChanging(value);
					this.SendPropertyChanging();
					this._plz = value;
					this.SendPropertyChanged("plz");
					this.OnplzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lieferanten_Artikel", Storage="_Artikels", ThisKey="lfnr", OtherKey="lfnr")]
		public EntitySet<Artikel> Artikels
		{
			get
			{
				return this._Artikels;
			}
			set
			{
				this._Artikels.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Artikels(Artikel entity)
		{
			this.SendPropertyChanging();
			entity.Lieferanten = this;
		}
		
		private void detach_Artikels(Artikel entity)
		{
			this.SendPropertyChanging();
			entity.Lieferanten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkte")]
	public partial class Produkte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pnr;
		
		private string _name;
		
		private EntitySet<Artikel> _Artikels;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpnrChanging(int value);
    partial void OnpnrChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Produkte()
		{
			this._Artikels = new EntitySet<Artikel>(new Action<Artikel>(this.attach_Artikels), new Action<Artikel>(this.detach_Artikels));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pnr
		{
			get
			{
				return this._pnr;
			}
			set
			{
				if ((this._pnr != value))
				{
					this.OnpnrChanging(value);
					this.SendPropertyChanging();
					this._pnr = value;
					this.SendPropertyChanged("pnr");
					this.OnpnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(1000)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkte_Artikel", Storage="_Artikels", ThisKey="pnr", OtherKey="pnr")]
		public EntitySet<Artikel> Artikels
		{
			get
			{
				return this._Artikels;
			}
			set
			{
				this._Artikels.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Artikels(Artikel entity)
		{
			this.SendPropertyChanging();
			entity.Produkte = this;
		}
		
		private void detach_Artikels(Artikel entity)
		{
			this.SendPropertyChanging();
			entity.Produkte = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auslieferung")]
	public partial class Auslieferung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _artnr;
		
		private int _menge;
		
		private int _kundennr;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnartnrChanging(int value);
    partial void OnartnrChanged();
    partial void OnmengeChanging(int value);
    partial void OnmengeChanged();
    partial void OnkundennrChanging(int value);
    partial void OnkundennrChanged();
    #endregion
		
		public Auslieferung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artnr", DbType="Int NOT NULL")]
		public int artnr
		{
			get
			{
				return this._artnr;
			}
			set
			{
				if ((this._artnr != value))
				{
					this.OnartnrChanging(value);
					this.SendPropertyChanging();
					this._artnr = value;
					this.SendPropertyChanged("artnr");
					this.OnartnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menge", DbType="Int NOT NULL")]
		public int menge
		{
			get
			{
				return this._menge;
			}
			set
			{
				if ((this._menge != value))
				{
					this.OnmengeChanging(value);
					this.SendPropertyChanging();
					this._menge = value;
					this.SendPropertyChanged("menge");
					this.OnmengeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kundennr", DbType="Int NOT NULL")]
		public int kundennr
		{
			get
			{
				return this._kundennr;
			}
			set
			{
				if ((this._kundennr != value))
				{
					this.OnkundennrChanging(value);
					this.SendPropertyChanging();
					this._kundennr = value;
					this.SendPropertyChanged("kundennr");
					this.OnkundennrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ArtikelDetailsView")]
	public partial class ArtikelDetailsView
	{
		
		private int _artnr;
		
		private int _lfnr;
		
		private int _pnr;
		
		private System.Nullable<int> _vorrat;
		
		private System.Nullable<decimal> _preis;
		
		private string _LieferantName;
		
		private string _LieferantEmail;
		
		private string _LieferantPlz;
		
		private string _ProduktName;
		
		public ArtikelDetailsView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artnr", DbType="Int NOT NULL")]
		public int artnr
		{
			get
			{
				return this._artnr;
			}
			set
			{
				if ((this._artnr != value))
				{
					this._artnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lfnr", DbType="Int NOT NULL")]
		public int lfnr
		{
			get
			{
				return this._lfnr;
			}
			set
			{
				if ((this._lfnr != value))
				{
					this._lfnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnr", DbType="Int NOT NULL")]
		public int pnr
		{
			get
			{
				return this._pnr;
			}
			set
			{
				if ((this._pnr != value))
				{
					this._pnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorrat", DbType="Int")]
		public System.Nullable<int> vorrat
		{
			get
			{
				return this._vorrat;
			}
			set
			{
				if ((this._vorrat != value))
				{
					this._vorrat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preis", DbType="Money")]
		public System.Nullable<decimal> preis
		{
			get
			{
				return this._preis;
			}
			set
			{
				if ((this._preis != value))
				{
					this._preis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferantName", DbType="VarChar(1000)")]
		public string LieferantName
		{
			get
			{
				return this._LieferantName;
			}
			set
			{
				if ((this._LieferantName != value))
				{
					this._LieferantName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferantEmail", DbType="VarChar(1000)")]
		public string LieferantEmail
		{
			get
			{
				return this._LieferantEmail;
			}
			set
			{
				if ((this._LieferantEmail != value))
				{
					this._LieferantEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferantPlz", DbType="NChar(5)")]
		public string LieferantPlz
		{
			get
			{
				return this._LieferantPlz;
			}
			set
			{
				if ((this._LieferantPlz != value))
				{
					this._LieferantPlz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktName", DbType="VarChar(1000)")]
		public string ProduktName
		{
			get
			{
				return this._ProduktName;
			}
			set
			{
				if ((this._ProduktName != value))
				{
					this._ProduktName = value;
				}
			}
		}
	}
	
	public partial class lagerbestandResult
	{
		
		private int _artnr;
		
		private string _Hersteller;
		
		private string _Produkt;
		
		private System.Nullable<int> _vorrat;
		
		private System.Nullable<decimal> _Wert;
		
		public lagerbestandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artnr", DbType="Int NOT NULL")]
		public int artnr
		{
			get
			{
				return this._artnr;
			}
			set
			{
				if ((this._artnr != value))
				{
					this._artnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hersteller", DbType="VarChar(1000)")]
		public string Hersteller
		{
			get
			{
				return this._Hersteller;
			}
			set
			{
				if ((this._Hersteller != value))
				{
					this._Hersteller = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Produkt", DbType="VarChar(1000)")]
		public string Produkt
		{
			get
			{
				return this._Produkt;
			}
			set
			{
				if ((this._Produkt != value))
				{
					this._Produkt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorrat", DbType="Int")]
		public System.Nullable<int> vorrat
		{
			get
			{
				return this._vorrat;
			}
			set
			{
				if ((this._vorrat != value))
				{
					this._vorrat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wert", DbType="Money")]
		public System.Nullable<decimal> Wert
		{
			get
			{
				return this._Wert;
			}
			set
			{
				if ((this._Wert != value))
				{
					this._Wert = value;
				}
			}
		}
	}
	
	public partial class ListeAlleArtikelZumLieferantenResult
	{
		
		private int _artnr;
		
		private int _lfnr;
		
		private int _pnr;
		
		private System.Nullable<int> _vorrat;
		
		private System.Nullable<decimal> _preis;
		
		private string _LieferantName;
		
		private string _LieferantEmail;
		
		private string _LieferantPlz;
		
		private string _ProduktName;
		
		public ListeAlleArtikelZumLieferantenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artnr", DbType="Int NOT NULL")]
		public int artnr
		{
			get
			{
				return this._artnr;
			}
			set
			{
				if ((this._artnr != value))
				{
					this._artnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lfnr", DbType="Int NOT NULL")]
		public int lfnr
		{
			get
			{
				return this._lfnr;
			}
			set
			{
				if ((this._lfnr != value))
				{
					this._lfnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnr", DbType="Int NOT NULL")]
		public int pnr
		{
			get
			{
				return this._pnr;
			}
			set
			{
				if ((this._pnr != value))
				{
					this._pnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorrat", DbType="Int")]
		public System.Nullable<int> vorrat
		{
			get
			{
				return this._vorrat;
			}
			set
			{
				if ((this._vorrat != value))
				{
					this._vorrat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preis", DbType="Money")]
		public System.Nullable<decimal> preis
		{
			get
			{
				return this._preis;
			}
			set
			{
				if ((this._preis != value))
				{
					this._preis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferantName", DbType="VarChar(1000)")]
		public string LieferantName
		{
			get
			{
				return this._LieferantName;
			}
			set
			{
				if ((this._LieferantName != value))
				{
					this._LieferantName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferantEmail", DbType="VarChar(1000)")]
		public string LieferantEmail
		{
			get
			{
				return this._LieferantEmail;
			}
			set
			{
				if ((this._LieferantEmail != value))
				{
					this._LieferantEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferantPlz", DbType="NChar(5)")]
		public string LieferantPlz
		{
			get
			{
				return this._LieferantPlz;
			}
			set
			{
				if ((this._LieferantPlz != value))
				{
					this._LieferantPlz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktName", DbType="VarChar(1000)")]
		public string ProduktName
		{
			get
			{
				return this._ProduktName;
			}
			set
			{
				if ((this._ProduktName != value))
				{
					this._ProduktName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
